### ISSUE TITLE
Failed to collect java classes

### ISSUE THREAD

**Issue by aphive** [noseglid/java-classpath-registry#7]
Installed this package and got the following error:

```
Failed to collect java classes
Only one open project supported.
Error: Only one open project supported.
    at readClassPath (/Users/username/.atom/packages/java-classpath-registry/lib/collector.js:79:27)
    at collect (/Users/username/.atom/packages/java-classpath-registry/lib/collector.js:146:10)
    at /Users/username/.atom/packages/java-classpath-registry/lib/main.js:20:16
```

I am using Atom 1.21.1 x64 on my MacBook Pro running High Sierra.

**Comment by aphive** [comment]
Never mind,  decided to go over all the other issues and saw this one with a different name that explains the same issue ...

https://github.com/noseglid/java-classpath-registry/issues/1
